language: generic
matrix:
    include:
        - os: osx
          osx_image: xcode9.4

before_install:
- |
    set -e
    brew update
    brew upgrade python
    pyvenv venv
    source venv/bin/activate
    set +e

install:
- |
    set -e
    PIP_INSTALL="python -m pip install"
    $PIP_INSTALL -U pip setuptools wheel
    set +e

script:
- |
    set -e -x
    builtin cd pybind11
    git checkout v2.2.3
    git bisect start v2.2.3 f7bc18f
    git bisect run ../bisect-test.sh
    echo "Done"
    set +e +x
